# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.IntegerField()),
                ('pFirstName', models.CharField(max_length=100)),
                ('pLastName', models.CharField(max_length=100)),
                ('pSex', models.CharField(max_length=20)),
                ('pTimeOfAdmission', models.DateTimeField(default=django.utils.timezone.now)),
                ('pCondition', models.CharField(max_length=50)),
                ('pBedType', models.CharField(max_length=50)),
                ('pModeOfArrival', models.CharField(max_length=50)),
                ('pAge', models.IntegerField()),
                ('pBirthDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pPhoneNo', models.CharField(max_length=12)),
                ('injuries', models.CharField(max_length=50)),
                ('deposition', models.CharField(max_length=50)),
                ('pTimeOfSurgery', models.DateTimeField(default=django.utils.timezone.now)),
                ('kinName', models.CharField(max_length=150)),
                ('relation', models.CharField(max_length=50)),
                ('pTimeOfDeath', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
