# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bedInfo',
            fields=[
                ('bedId', models.AutoField(primary_key=True, serialize=False)),
                ('bedType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('hospitalId', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=250)),
                ('hospitalPhoneNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='nurse',
            fields=[
                ('nurseId', models.AutoField(primary_key=True, serialize=False)),
                ('nFirstName', models.CharField(default='Nurse first name', max_length=100, verbose_name="Nurse's first name")),
                ('nLastName', models.CharField(default='Nurse last name', max_length=100, verbose_name="Nurse's first name")),
                ('nAddress', models.CharField(max_length=250)),
                ('nPhoneNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='nurseBed',
            fields=[
                ('nurseBedId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pFirstName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pLastName',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pSex',
        ),
        migrations.AddField(
            model_name='patient',
            name='firstName',
            field=models.CharField(default='Patients first name', max_length=100, verbose_name="Patient's first name"),
        ),
        migrations.AddField(
            model_name='patient',
            name='lastName',
            field=models.CharField(default='Patients last name', max_length=100, verbose_name="Patient's last name"),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='Male/Female/Other', max_length=20, verbose_name="Patient's sex"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pCondition',
            field=models.CharField(default='Patients initial condition', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
