# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0002_auto_20171020_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pTimeOfDeath',
            field=models.DateTimeField(),
        ),
    ]
