# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0003_auto_20170930_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='admin_id',
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.CharField(max_length=50),
        ),
    ]
