# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0003_auto_20171020_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pTimeOfDeath',
            field=models.DateTimeField(blank=True),
        ),
    ]
