# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0006_auto_20171021_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
