# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0007_auto_20171021_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='id',
        ),
        migrations.AddField(
            model_name='administrator',
            name='admin_id',
            field=models.AutoField(default=101, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
