# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0008_auto_20171021_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse_id',
            field=models.AutoField(default=5001, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=6001, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
