# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eBedTrack', '0010_auto_20171021_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.IntegerField(default=501, primary_key=True, serialize=False)),
                ('bed_type', models.CharField(max_length=50)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosbeds', to='eBedTrack.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bed_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
